### ISSUE TITLE
--- Logging error ---

### ISSUE THREAD

**Issue by cod3gen** [elagil/sigmadsp#36]
Hi @elagil,

Thank you for your awesome work on this module. While trying it out on a very simple input -> output project in sigmastudio for ADAU1466 i have stumbled across a issue in logging functions, Please see the message below;

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: %x format: an integer is required, not Field
Call stack:
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp-2.0.2-py3.9.egg/sigmadsp/backend.py", line 196, in sigma_tcp_server_worker
    self.sigma_tcp_server.serve_forever()
  File "/usr/lib/python3.9/socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp-2.0.2-py3.9.egg/sigmadsp/sigmastudio/server.py", line 194, in handle
    self.handle_write_request(packet)
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp-2.0.2-py3.9.egg/sigmadsp/sigmastudio/server.py", line 142, in handle_write_request
    logger.info("[write] %s bytes to address 0x%04x", packet.header["data_length"], packet.header["address"])
Message: '[write] %s bytes to address 0x%04x'
Arguments: (Field(name='data_length', offset=8, size=4), Field(name='address', offset=12, size=2))
```

Any ideas for a solution on this? Stock configfile other than that hard reset pin is changed to correct one in my case.

**Comment by elagil** [comment]
Hi @cod3gen! I'm glad to hear that you like the project. I will investigate the issue, I have not seen it before. I guess you see that error message when you write something to the DSP via SigmaStudio?

**Comment by elagil** [comment]
I must have missed this while testing. Please try the new [release](https://github.com/elagil/sigmadsp/releases/tag/v2.0.3) by upgrading with `sudo pip3 install sigmadsp --upgrade`.

**Comment by elagil** [comment]
@cod3gen Since you are using the formerly untested ADAU1466, please let me know if you find some issues particular to that chip. I hope not, since it has the same register set as my ADAU1452.

**Comment by cod3gen** [comment]
Perfect @elagil, works great now 👍 

Will let you know if i come across any issues on 1466.
