### ISSUE TITLE
Payload length does not match the expected length

### ISSUE THREAD

**Issue by cod3gen** [elagil/sigmadsp#38]
**Describe the bug**
Writing seems to work(using a blinking led only to verify), however when i try to read a LevelRTA meter(or any other read methods it seems, including chip data in register controls page) as an example, it throws an error like this:

```
----------------------------------------
Exception occurred during processing of request from ('192.168.1.70', 53426)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp/sigmastudio/server.py", line 197, in handle
    packet = self.new_packet()
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp/sigmastudio/server.py", line 188, in new_packet
    return Packet(header, payload)
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp/sigmastudio/server.py", line 36, in __init__
    self.payload = payload
  File "/usr/local/lib/python3.9/dist-packages/sigmadsp/sigmastudio/server.py", line 55, in payload
    assert (
AssertionError: Payload length does not match the expected length.
----------------------------------------
```

**To Reproduce**
https://prnt.sc/DeZwPu_RPXZh

**Expected behavior**
Readback data

**Version**
Latest 2.0.3 @ ADAU1466 Chip

**Comment by elagil** [comment]
I can reproduce. This project needs more automated testing ;)

**Comment by elagil** [comment]
@cod3gen Should now be fixed in https://github.com/elagil/sigmadsp/releases/tag/v2.0.4

**Comment by cod3gen** [comment]
@elagil Thanks for the fix :-)

I did notice that Sigmastudio is crashing when doing some register read outs, but this is probably an error on sigmastudio, your module responds correctly it seems 👍 

Will let you know if i find some other issues, but it seems to working fine on ADAU1466.

**Comment by elagil** [comment]
@cod3gen Yes, there is some ongoing discussion that I saw in the AD forums: https://ez.analog.com/dsp/sigmadsp/f/q-a/115184/bug-report-sigma-studio-tcp-ip-read-from-dsp-with-temporary-solution/399156

Hopefully, it gets resolved at some point.
